spring:
  application:
    name: nutridata
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    #sql:
      #init:
      #mode: always # cambiar a always
    #schema-locations: classpath:schema.sql
